name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libeigen3-dev libgtest-dev cmake
        
    - name: Build Google Test
      run: |
        cd /usr/src/googletest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib
        
    - name: Setup Makefile
      run: |
        mkdir -p bin
        printf "CXX = g++\n" > Makefile
        printf "CXXFLAGS = -std=c++17 -O3 -march=native -Wall -Wextra -I/usr/include/eigen3\n" >> Makefile
        printf "GTEST_LIBS = -lgtest -lgtest_main -lpthread\n\n" >> Makefile
        printf "SRC = main.cpp csv_utils.cpp gauss.cpp random_generator.cpp\n" >> Makefile
        printf "TEST_SRC = test.cpp\n\n" >> Makefile
        printf "all: bin/gauss_app bin/gauss_tests\n\n" >> Makefile
        printf "bin/gauss_app: \$(SRC)\n" >> Makefile
        printf "\t@mkdir -p bin\n" >> Makefile
        printf "\t\$(CXX) \$(CXXFLAGS) \$\^ -o \$\@\n\n" >> Makefile
        printf "bin/gauss_tests: \$(TEST_SRC) \$(filter-out main.cpp, \$(SRC))\n" >> Makefile
        printf "\t@mkdir -p bin\n" >> Makefile
        printf "\t\$(CXX) \$(CXXFLAGS) \$\^ \$(GTEST_LIBS) -o \$\@\n\n" >> Makefile
        printf "test: bin/gauss_tests\n" >> Makefile
        printf "\t./bin/gauss_tests\n\n" >> Makefile
        printf "clean:\n" >> Makefile
        printf "\trm -rf bin/*\n\n" >> Makefile
        printf ".PHONY: all test clean\n" >> Makefile
        
    - name: Build project
      run: |
        make clean
        make
      
    - name: Run tests
      run: |
        make test
      
    - name: Verify solver
      run: |
        ./bin/generate_system 5 test_system.csv
        ./bin/gauss_solver test_system.csv solution.csv
        cat solution.csv
