name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libeigen3-dev libgtest-dev cmake
        
    - name: Сборка Google Test
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/libgtest*.a /usr/lib
        
    - name: Компиляция основной программы
      run: |
        mkdir -p bin
        g++ -std=c++17 -O3 -march=native -Wall -Wextra -I/usr/include/eigen3 \
            main.cpp csv_utils.cpp gauss.cpp random_generator.cpp \
            -o bin/gauss_app
            
    - name: Компиляция тестов
      run: |
        g++ -std=c++17 -O3 -march=native -Wall -Wextra -I/usr/include/eigen3 \
            test.cpp csv_utils.cpp gauss.cpp random_generator.cpp \
            -lgtest -lgtest_main -lpthread \
            -o bin/gauss_tests
            
    - name: Запуск тестов
      run: |
        ./bin/gauss_tests
      
    - name: Проверка решения
      run: |
        ./bin/gauss_app 5 test_system.csv solution.csv
        cat solution.csv
