name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libeigen3-dev libgtest-dev cmake
        
    - name: Build Google Test
      run: |
        cd /usr/src/googletest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib
        
    - name: Setup project structure
      run: |
        mkdir -p src test
        mv *.cpp src/ 2>/dev/null || true
        mv *.h src/ 2>/dev/null || true
        mv test.cpp test/ 2>/dev/null || true
        
    - name: Create Makefile
      run: |
        mkdir -p bin
        echo "CXX = g++" > Makefile
        echo "CXXFLAGS = -std=c++17 -O3 -march=native -Wall -Wextra -I/usr/include/eigen3" >> Makefile
        echo "GTEST_LIBS = -lgtest -lgtest_main -lpthread" >> Makefile
        echo "" >> Makefile
        echo "COMMON_SRC = src/csv_utils.cpp src/gauss.cpp src/random_generator.cpp" >> Makefile
        echo "SOLVER_SRC = src/solver_main.cpp \$(COMMON_SRC)" >> Makefile
        echo "GENERATOR_SRC = src/generator_main.cpp \$(COMMON_SRC)" >> Makefile
        echo "TEST_SRC = test/test_gauss.cpp \$(COMMON_SRC)" >> Makefile
        echo "" >> Makefile
        echo "all: bin/solver bin/generator bin/gauss_tests" >> Makefile
        echo "" >> Makefile
        echo "bin/solver: \$(SOLVER_SRC)" >> Makefile
        echo -e "\t@mkdir -p bin" >> Makefile
        echo -e "\t\$(CXX) \$(CXXFLAGS) \$^ -o \$@" >> Makefile
        echo "" >> Makefile
        echo "bin/generator: \$(GENERATOR_SRC)" >> Makefile
        echo -e "\t@mkdir -p bin" >> Makefile
        echo -e "\t\$(CXX) \$(CXXFLAGS) \$^ -o \$@" >> Makefile
        echo "" >> Makefile
        echo "bin/gauss_tests: \$(TEST_SRC)" >> Makefile
        echo -e "\t@mkdir -p bin" >> Makefile
        echo -e "\t\$(CXX) \$(CXXFLAGS) \$^ \$(GTEST_LIBS) -o \$@" >> Makefile
        echo "" >> Makefile
        echo "test: bin/gauss_tests" >> Makefile
        echo -e "\t./bin/gauss_tests" >> Makefile
        echo "" >> Makefile
        echo "clean:" >> Makefile
        echo -e "\trm -rf bin/*" >> Makefile
        echo "" >> Makefile
        echo ".PHONY: all test clean" >> Makefile
        
    - name: Build project
      run: make
      
    - name: Run tests
      run: make test
      
    - name: Verify solver
      run: |
        ./bin/generator 5 test_system.csv
        ./bin/solver test_system.csv solution.csv
        cat solution.csv
