name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libeigen3-dev libgtest-dev cmake
        
    - name: Build Google Test
      run: |
        cd /usr/src/googletest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib
        
    - name: Setup Makefile
      run: |
        mkdir -p bin
        cat << 'EOF' > Makefile
CXX = g++
CXXFLAGS = -std=c++17 -O3 -march=native -Wall -Wextra -I/usr/include/eigen3
GTEST_LIBS = -lgtest -lgtest_main -lpthread

SRC = main.cpp csv_utils.cpp gauss.cpp random_generator.cpp
TEST_SRC = test.cpp

all: bin/gauss_app bin/gauss_tests

bin/gauss_app: $(SRC)
	@mkdir -p bin
	$(CXX) $(CXXFLAGS) $^ -o $@

bin/gauss_tests: $(TEST_SRC) $(filter-out main.cpp, $(SRC))
	@mkdir -p bin
	$(CXX) $(CXXFLAGS) $^ $(GTEST_LIBS) -o $@

test: bin/gauss_tests
	./bin/gauss_tests

clean:
	rm -rf bin/*

.PHONY: all test clean
EOF
        
    - name: Verify Makefile
      run: |
        cat Makefile
        make --dry-run
        
    - name: Build project
      run: |
        make clean
        make all
      
    - name: Run tests
      run: |
        make test
      
    - name: Verify solver
      run: |
        ./bin/gauss_app 5 test_system.csv solution.csv
        cat solution.csv
